// frontend/src/lib/views/stats/AITab.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { queryDb, queryAll } from '../../db';
  import {
    TRACES_SQL, TRACE_DETAIL_SQL, TRACE_TOOL_CALLS_SQL, TRACE_TOOL_RESPONSES_SQL,
    AI_TOKENS_OVER_TIME_BY_MODEL_SQL, AI_MODEL_USAGE_SQL,
  } from '../../sql';
  import { colors, modelColor } from '../../css-var';
  import { BarChart, PieChart } from 'layerchart';
  import type { TraceSummary, TraceModelCall, ToolCallEntry, ToolResponseEntry, DetailSelection } from '../../types';
  import StatCards from './StatCards.svelte';
  import DetailPanel from './DetailPanel.svelte';

  let traces = $state<TraceSummary[]>([]);
  let expandedTraces = $state<Set<string>>(new Set());
  let traceDetails = $state<Map<string, TraceModelCall[]>>(new Map());
  let traceToolCalls = $state<Map<string, ToolCallEntry[]>>(new Map());
  let traceToolResponses = $state<Map<string, ToolResponseEntry[]>>(new Map());
  let detail = $state<DetailSelection | null>(null);
  let loaded = $state(false);

  interface PieSeries { key: string; color: string; data: { key: string; value: number }[] }
  interface PieLegend { label: string; color: string; value: string }

  // Chart data
  let tokTimeData = $state<Record<string, unknown>[]>([]);
  let tokTimeSeries = $state<{ key: string; label: string; color: string }[]>([]);
  let tokenTypeSeries = $state<PieSeries[]>([]);
  let tokenTypeLegend = $state<PieLegend[]>([]);
  let tokenTypeTotal = $state('');
  let modelTokenSeries = $state<PieSeries[]>([]);
  let modelTokenLegend = $state<PieLegend[]>([]);
  let modelTokenTotal = $state('');
  let modelCostSeries = $state<PieSeries[]>([]);
  let modelCostLegend = $state<PieLegend[]>([]);
  let modelCostTotal = $state('');
  let statCards = $state<{ label: string; value: string | number; colorClass?: string }[]>([]);

  onMount(() => {
    Promise.all([loadTraces(), loadCharts()]).then(() => { loaded = true; });
  });

  async function loadTraces() {
    try {
      traces = queryAll<TraceSummary>(await queryDb(TRACES_SQL, [50]));
    } catch (e) { console.error('Failed to load traces:', e); }
  }

  async function loadCharts() {
    try {
      const [tokTimeRes, modelRes] = await Promise.all([
        queryDb(AI_TOKENS_OVER_TIME_BY_MODEL_SQL),
        queryDb(AI_MODEL_USAGE_SQL),
      ]);

      // Tokens over time -- one bar per call, stacked by model
      const tokRows = queryAll<{ bucket: number; model: string; provider: string; tokens: number }>(tokTimeRes);
      // Build model->provider map from raw rows (first occurrence wins)
      const modelProviderMap = new Map<string, string>();
      for (const r of tokRows) {
        if (!modelProviderMap.has(r.model)) modelProviderMap.set(r.model, r.provider);
      }
      const models = [...modelProviderMap.keys()];
      const buckets = [...new Set(tokRows.map(r => r.bucket))].sort((a, b) => a - b);
      // Register colors for all models (provider-aware) before building series
      for (const m of models) modelColor(m, modelProviderMap.get(m)!);
      tokTimeSeries = models.map(m => ({ key: m, label: m, color: modelColor(m, modelProviderMap.get(m)!) }));
      tokTimeData = buckets.map((b, i) => {
        const row: Record<string, unknown> = { bucket: String(i + 1) };
        for (const m of models) {
          row[m] = tokRows.find(r => r.bucket === b && r.model === m)?.tokens ?? 0;
        }
        return row;
      });

      // Model usage -- build pie series for all three charts
      const modelRows = queryAll<{ model: string; provider: string; input_tokens: number; output_tokens: number; tokens: number; cost: number; call_count: number }>(modelRes);
      for (const r of modelRows) modelColor(r.model, r.provider);

      // Token type pie (input vs output)
      const totalIn = modelRows.reduce((s, r) => s + r.input_tokens, 0);
      const totalOut = modelRows.reduce((s, r) => s + r.output_tokens, 0);
      const ttSeries: PieSeries[] = [];
      if (totalIn > 0) ttSeries.push({ key: 'Input', color: colors.tokenInput, data: [{ key: 'Input', value: totalIn }] });
      if (totalOut > 0) ttSeries.push({ key: 'Output', color: colors.tokenOutput, data: [{ key: 'Output', value: totalOut }] });
      tokenTypeSeries = ttSeries;
      tokenTypeLegend = [
        { label: 'Input', color: colors.tokenInput, value: fmtTokens(totalIn) },
        { label: 'Output', color: colors.tokenOutput, value: fmtTokens(totalOut) },
      ];
      tokenTypeTotal = fmtTokens(totalIn + totalOut);

      // Tokens per model pie
      modelTokenSeries = modelRows.filter(r => r.tokens > 0).map(r => ({
        key: r.model,
        color: modelColor(r.model, r.provider),
        data: [{ key: r.model, value: r.tokens }],
      }));
      modelTokenLegend = modelRows.filter(r => r.tokens > 0).map(r => ({
        label: r.model, color: modelColor(r.model, r.provider), value: fmtTokens(r.tokens),
      }));
      modelTokenTotal = fmtTokens(modelRows.reduce((s, r) => s + r.tokens, 0));

      // Cost per model pie
      const totalCostVal = modelRows.reduce((s, r) => s + r.cost, 0);
      modelCostSeries = modelRows.filter(r => r.cost > 0).map(r => ({
        key: r.model,
        color: modelColor(r.model, r.provider),
        data: [{ key: r.model, value: r.cost }],
      }));
      modelCostLegend = modelRows.filter(r => r.cost > 0).map(r => ({
        label: r.model, color: modelColor(r.model, r.provider), value: '$' + r.cost.toFixed(3),
      }));
      modelCostTotal = '$' + totalCostVal.toFixed(2);

      // Stat cards
      const callCount = modelRows.reduce((s, r) => s + r.call_count, 0);
      statCards = [
        { label: 'Calls', value: callCount },
        { label: 'Tokens In', value: fmtTokens(totalIn) },
        { label: 'Tokens Out', value: fmtTokens(totalOut) },
        { label: 'Cost', value: totalCostVal < 0.01 && totalCostVal > 0 ? '<$0.01' : '$' + totalCostVal.toFixed(2) },
      ];
    } catch (e) { console.error('AI charts failed:', e); }
  }

  async function toggleTrace(traceId: string) {
    const next = new Set(expandedTraces);
    if (next.has(traceId)) { next.delete(traceId); expandedTraces = next; return; }
    next.add(traceId);
    expandedTraces = next;
    if (!traceDetails.has(traceId)) {
      try {
        const [detailRes, tcRes, trRes] = await Promise.all([
          queryDb(TRACE_DETAIL_SQL, [traceId]),
          queryDb(TRACE_TOOL_CALLS_SQL, [traceId]),
          queryDb(TRACE_TOOL_RESPONSES_SQL, [traceId]),
        ]);
        traceDetails = new Map(traceDetails).set(traceId, queryAll<TraceModelCall>(detailRes));
        traceToolCalls = new Map(traceToolCalls).set(traceId, queryAll<ToolCallEntry>(tcRes));
        traceToolResponses = new Map(traceToolResponses).set(traceId, queryAll<ToolResponseEntry>(trRes));
      } catch (e) { console.error('Failed to load trace detail:', e); }
    }
  }

  function fmtTokens(n: number): string {
    if (n >= 1_000_000) return (n / 1_000_000).toFixed(1) + 'M';
    if (n >= 1_000) return (n / 1_000).toFixed(1) + 'K';
    return String(n);
  }

  function fmtDuration(ms: number): string {
    if (ms >= 60_000) return (ms / 60_000).toFixed(1) + 'm';
    if (ms >= 1_000) return (ms / 1_000).toFixed(1) + 's';
    return ms + 'ms';
  }

  function provColor(provider: string | null): string {
    switch (provider) {
      case 'anthropic': return 'text-provider-anthropic';
      case 'google': return 'text-provider-google';
      case 'openai': return 'text-provider-openai';
      case 'mistral': return 'text-provider-mistral';
      default: return 'text-provider-fallback';
    }
  }

  function truncate(text: string | null, len: number): string {
    if (!text) return '';
    return text.length <= len ? text : text.substring(0, len) + '...';
  }

  function selectThinking(call: TraceModelCall) { detail = { type: 'thinking', data: { thinking_content: call.thinking_content } }; }
  function selectText(call: TraceModelCall) { detail = { type: 'text', data: { text_content: call.text_content } }; }
  function selectTool(tc: ToolCallEntry, traceId: string) {
    const resp = (traceToolResponses.get(traceId) ?? []).find(r => r.call_id === tc.call_id);
    detail = { type: 'tool', data: { tool_name: tc.tool_name, arguments: tc.arguments, origin: tc.origin, content_preview: resp?.content_preview ?? undefined, is_error: resp?.is_error ?? 0 } };
  }
  function callToolCalls(traceId: string, modelCallId: number): ToolCallEntry[] {
    return (traceToolCalls.get(traceId) ?? []).filter(tc => tc.model_call_id === modelCallId);
  }
</script>

<div class="flex h-full overflow-hidden">
  <div class="flex-1 min-w-0 flex flex-col overflow-hidden">
    {#if statCards.length > 0}
      <StatCards cards={statCards} />
    {/if}

    <div class="flex-1 min-h-0 overflow-auto">
    <!-- Charts: tokens over time bar + 3 pie charts -->
    <div class="space-y-2 px-3 pb-1">
      <div class="bg-base-200/30 rounded-lg p-2">
        <div class="text-[10px] font-semibold text-base-content/40 uppercase tracking-wider mb-1">Tokens Over Time</div>
        <div class="h-44 w-full">
          {#if tokTimeData.length > 0}
            <BarChart data={tokTimeData} x="bucket" series={tokTimeSeries} seriesLayout="stack" props={{ legend: { placement: 'bottom' } }} />
          {/if}
        </div>
      </div>
      <div class="grid grid-cols-3 gap-3">
        <!-- Token Type (input vs output) -->
        <div class="bg-base-200/30 rounded-lg p-2">
          <div class="text-[10px] font-semibold text-base-content/40 uppercase tracking-wider mb-1">Token Type</div>
          {#if tokenTypeSeries.length > 0}
            <div class="relative">
              <div class="h-32 w-full">
                <PieChart key="key" value="value" innerRadius={35} series={tokenTypeSeries} />
              </div>
              <div class="absolute inset-0 h-32 flex items-center justify-center pointer-events-none">
                <span class="text-sm font-bold text-base-content/70">{tokenTypeTotal}</span>
              </div>
            </div>
            <div class="flex flex-wrap gap-x-3 gap-y-0.5 mt-1 justify-center">
              {#each tokenTypeLegend as item}
                <div class="flex items-center gap-1 text-[10px]">
                  <span class="w-2 h-2 rounded-full shrink-0" style="background:{item.color}"></span>
                  <span class="text-base-content/50">{item.label}</span>
                  <span class="text-base-content/70 font-medium">{item.value}</span>
                </div>
              {/each}
            </div>
          {/if}
        </div>
        <!-- Tokens per model -->
        <div class="bg-base-200/30 rounded-lg p-2">
          <div class="text-[10px] font-semibold text-base-content/40 uppercase tracking-wider mb-1">Tokens Per Model</div>
          {#if modelTokenSeries.length > 0}
            <div class="relative">
              <div class="h-32 w-full">
                <PieChart key="key" value="value" innerRadius={35} series={modelTokenSeries} />
              </div>
              <div class="absolute inset-0 h-32 flex items-center justify-center pointer-events-none">
                <span class="text-sm font-bold text-base-content/70">{modelTokenTotal}</span>
              </div>
            </div>
            <div class="flex flex-col gap-0.5 mt-1">
              {#each modelTokenLegend as item}
                <div class="flex items-center gap-1 text-[10px]">
                  <span class="w-2 h-2 rounded-full shrink-0" style="background:{item.color}"></span>
                  <span class="text-base-content/50 truncate">{item.label}</span>
                  <span class="text-base-content/70 font-medium ml-auto shrink-0">{item.value}</span>
                </div>
              {/each}
            </div>
          {/if}
        </div>
        <!-- Cost per model -->
        <div class="bg-base-200/30 rounded-lg p-2">
          <div class="text-[10px] font-semibold text-base-content/40 uppercase tracking-wider mb-1">Cost Per Model</div>
          {#if modelCostSeries.length > 0}
            <div class="relative">
              <div class="h-32 w-full">
                <PieChart key="key" value="value" innerRadius={35} series={modelCostSeries} />
              </div>
              <div class="absolute inset-0 h-32 flex items-center justify-center pointer-events-none">
                <span class="text-sm font-bold text-base-content/70">{modelCostTotal}</span>
              </div>
            </div>
            <div class="flex flex-col gap-0.5 mt-1">
              {#each modelCostLegend as item}
                <div class="flex items-center gap-1 text-[10px]">
                  <span class="w-2 h-2 rounded-full shrink-0" style="background:{item.color}"></span>
                  <span class="text-base-content/50 truncate">{item.label}</span>
                  <span class="text-base-content/70 font-medium ml-auto shrink-0">{item.value}</span>
                </div>
              {/each}
            </div>
          {:else}
            <div class="flex items-center justify-center h-32 text-base-content/30 text-xs">No cost data</div>
          {/if}
        </div>
      </div>
    </div>

    <!-- Trace viewer -->
    {#if !loaded}
      <div class="flex items-center justify-center h-32"><span class="loading loading-spinner loading-md"></span></div>
    {:else if traces.length === 0}
      <div class="flex items-center justify-center h-32 text-base-content/40 text-sm">No traces recorded yet.</div>
    {:else}
      <table class="w-full text-xs">
        <thead>
          <tr class="text-base-content/40 border-b border-base-200">
            <th class="pl-3 pr-1 py-1.5 w-5"></th>
            <th class="py-1.5 pr-2 text-left font-medium">Provider</th>
            <th class="py-1.5 pr-2 text-left font-medium">Model</th>
            <th class="py-1.5 pr-2 text-right font-medium">In</th>
            <th class="py-1.5 pr-2 text-right font-medium">Out</th>
            <th class="py-1.5 pr-2 text-right font-medium">Tools</th>
            <th class="py-1.5 pr-2 text-right font-medium">Time</th>
            <th class="py-1.5 pr-3 text-right font-medium">Cost</th>
          </tr>
        </thead>
        <tbody>
          {#each traces as trace}
            {@const isExpanded = expandedTraces.has(trace.trace_id)}
            {@const calls = traceDetails.get(trace.trace_id) ?? []}
            <tr class="hover:bg-base-200/40 cursor-pointer transition-colors border-b border-base-200" onclick={() => toggleTrace(trace.trace_id)}>
              <td class="pl-3 pr-1 py-2 w-5">
                <svg class="size-3 transition-transform {isExpanded ? 'rotate-90' : ''}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="9 18 15 12 9 6"/></svg>
              </td>
              <td class="py-2 pr-2 whitespace-nowrap font-medium {provColor(trace.provider)}">{trace.provider ?? 'unknown'}</td>
              <td class="py-2 pr-2 font-mono text-base-content/70">{trace.model ?? '?'}</td>
              <td class="py-2 pr-2 whitespace-nowrap text-base-content/50 text-right">{fmtTokens(trace.total_input_tokens)} in</td>
              <td class="py-2 pr-2 whitespace-nowrap text-base-content/50 text-right">{fmtTokens(trace.total_output_tokens)} out</td>
              <td class="py-2 pr-2 whitespace-nowrap text-base-content/40 text-right">{trace.total_tool_calls > 0 ? `${trace.total_tool_calls} tools` : ''}</td>
              <td class="py-2 pr-2 whitespace-nowrap text-base-content/40 font-mono text-right">{trace.total_duration_ms ? fmtDuration(trace.total_duration_ms) : ''}</td>
              <td class="py-2 pr-3 whitespace-nowrap text-base-content/40 font-mono text-right">${trace.total_cost.toFixed(3)}</td>
            </tr>
            {#if isExpanded}
              {#each calls as call}
                {@const toolCalls = callToolCalls(trace.trace_id, call.id)}
                {#if call.thinking_content}
                  <tr class="bg-base-200/20 hover:bg-base-300/30 cursor-pointer transition-colors" onclick={() => selectThinking(call)}>
                    <td></td>
                    <td class="py-1 pr-2"><span class="badge badge-xs w-10 text-center bg-span-thinking/15 text-span-thinking border-0">think</span></td>
                    <td class="py-1 text-base-content/50 truncate max-w-0" colspan="6">{truncate(call.thinking_content, 100)}</td>
                  </tr>
                {/if}
                {#each toolCalls as tc}
                  <tr class="bg-base-200/20 hover:bg-base-300/30 cursor-pointer transition-colors" onclick={() => selectTool(tc, trace.trace_id)}>
                    <td></td>
                    <td class="py-1 pr-2"><span class="badge badge-xs w-10 text-center bg-span-tool/15 text-span-tool border-0">tool</span></td>
                    <td class="py-1 font-mono text-base-content/70 whitespace-nowrap pr-2">{tc.tool_name}</td>
                    <td class="py-1 text-base-content/30 truncate max-w-0" colspan="5">{truncate(tc.arguments, 60)}</td>
                  </tr>
                {/each}
                {#if call.text_content}
                  <tr class="bg-base-200/20 hover:bg-base-300/30 cursor-pointer transition-colors" onclick={() => selectText(call)}>
                    <td></td>
                    <td class="py-1 pr-2"><span class="badge badge-xs w-10 text-center bg-span-answer/15 text-span-answer border-0">text</span></td>
                    <td class="py-1 text-base-content/50 truncate max-w-0" colspan="6">{truncate(call.text_content, 100)}</td>
                  </tr>
                {/if}
                {#if !call.thinking_content && !call.text_content && callToolCalls(trace.trace_id, call.id).length === 0}
                  <tr class="bg-base-200/20"><td></td><td class="py-1 pr-2"></td><td class="py-1 text-base-content/30 italic" colspan="6">no content captured</td></tr>
                {/if}
              {/each}
            {/if}
          {/each}
        </tbody>
      </table>
    {/if}
    </div>
  </div>

  {#if detail}
    <DetailPanel selection={detail} onClose={() => { detail = null; }} />
  {/if}
</div>

// frontend/src/lib/views/stats/AITab.tsx
// AITab -- AI model usage charts + trace viewer
import { useState, useEffect, useMemo, useCallback } from 'react';
import {
  BarChart, Bar, XAxis, YAxis, Tooltip, Legend, ResponsiveContainer,
  PieChart, Pie, Cell,
} from 'recharts';
import { queryDb, queryAll, queryOne } from '../../db';
import {
  AI_USAGE_PER_PROVIDER_SQL, AI_TOKENS_OVER_TIME_BY_MODEL_SQL,
  AI_MODEL_USAGE_SQL, TRACES_SQL, TRACE_DETAIL_SQL,
  TRACE_TOOL_CALLS_SQL, TRACE_TOOL_RESPONSES_SQL,
} from '../../sql';
import { providerColor, modelColor, colors } from '../../css-var';
import StatCards from './StatCards';
import DetailPanel from './DetailPanel';
import type { TraceSummary, TraceModelCall, ToolCallEntry, ToolResponseEntry, DetailSelection } from '../../types';
import { ChevronRight, ChevronDown } from '../../icons/Icons';

interface ProviderUsage {
  provider: string;
  input_tokens: number;
  output_tokens: number;
  cost: number;
  call_count: number;
}

interface ModelUsage {
  model: string;
  provider: string;
  input_tokens: number;
  output_tokens: number;
  tokens: number;
  cost: number;
  call_count: number;
}

interface TokenOverTime {
  bucket: number;
  model: string;
  provider: string;
  tokens: number;
}

function fmtTokens(n: number): string {
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(1) + 'M';
  if (n >= 1_000) return (n / 1_000).toFixed(1) + 'K';
  return String(n);
}

function fmtCost(n: number): string {
  if (n < 0.01 && n > 0) return '<$0.01';
  return '$' + n.toFixed(4);
}

function fmtDuration(ms: number): string {
  if (ms >= 60_000) return (ms / 60_000).toFixed(1) + 'm';
  if (ms >= 1000) return (ms / 1000).toFixed(1) + 's';
  return ms + 'ms';
}

export default function AITab() {
  const [providers, setProviders] = useState<ProviderUsage[]>([]);
  const [models, setModels] = useState<ModelUsage[]>([]);
  const [tokenTimeline, setTokenTimeline] = useState<Record<string, unknown>[]>([]);
  const [traces, setTraces] = useState<TraceSummary[]>([]);
  const [expandedTrace, setExpandedTrace] = useState<string | null>(null);
  const [traceCalls, setTraceCalls] = useState<TraceModelCall[]>([]);
  const [traceToolCalls, setTraceToolCalls] = useState<ToolCallEntry[]>([]);
  const [traceToolResponses, setTraceToolResponses] = useState<ToolResponseEntry[]>([]);
  const [detail, setDetail] = useState<DetailSelection | null>(null);

  const loadData = useCallback(async () => {
    try {
      const [provResult, modelResult, tokenResult, traceResult] = await Promise.all([
        queryDb(AI_USAGE_PER_PROVIDER_SQL),
        queryDb(AI_MODEL_USAGE_SQL),
        queryDb(AI_TOKENS_OVER_TIME_BY_MODEL_SQL),
        queryDb(TRACES_SQL, [50]),
      ]);
      setProviders(queryAll<ProviderUsage>(provResult));
      setModels(queryAll<ModelUsage>(modelResult));
      setTraces(queryAll<TraceSummary>(traceResult));

      // Pivot token timeline by model
      const raw = queryAll<TokenOverTime>(tokenResult);
      const allModels = [...new Set(raw.map((r) => r.model))];
      const bucketMap = new Map<number, Record<string, unknown>>();
      for (const r of raw) {
        if (!bucketMap.has(r.bucket)) bucketMap.set(r.bucket, { bucket: r.bucket });
        const row = bucketMap.get(r.bucket)!;
        row[r.model] = ((row[r.model] as number) ?? 0) + r.tokens;
        // Store provider for color lookup
        row[`__provider_${r.model}`] = r.provider;
      }
      setTokenTimeline(Array.from(bucketMap.values()));
    } catch (e) {
      console.error('AITab load failed:', e);
    }
  }, []);

  useEffect(() => {
    loadData();
    const iv = setInterval(loadData, 5000);
    return () => clearInterval(iv);
  }, [loadData]);

  // Load trace detail when expanding
  const toggleTrace = useCallback(async (traceId: string) => {
    if (expandedTrace === traceId) {
      setExpandedTrace(null);
      setTraceCalls([]);
      setTraceToolCalls([]);
      setTraceToolResponses([]);
      setDetail(null);
      return;
    }
    setExpandedTrace(traceId);
    try {
      const [callResult, toolResult, respResult] = await Promise.all([
        queryDb(TRACE_DETAIL_SQL, [traceId]),
        queryDb(TRACE_TOOL_CALLS_SQL, [traceId]),
        queryDb(TRACE_TOOL_RESPONSES_SQL, [traceId]),
      ]);
      setTraceCalls(queryAll<TraceModelCall>(callResult));
      setTraceToolCalls(queryAll<ToolCallEntry>(toolResult));
      setTraceToolResponses(queryAll<ToolResponseEntry>(respResult));
    } catch (e) {
      console.error('Trace detail load failed:', e);
    }
  }, [expandedTrace]);

  const totalTokens = useMemo(() => providers.reduce((s, p) => s + p.input_tokens + p.output_tokens, 0), [providers]);
  const totalCost = useMemo(() => providers.reduce((s, p) => s + p.cost, 0), [providers]);
  const totalCalls = useMemo(() => providers.reduce((s, p) => s + p.call_count, 0), [providers]);
  const modelNames = useMemo(() => [...new Set(models.map((m) => m.model))], [models]);

  // Pie chart data for cost by provider
  const costPieData = useMemo(() =>
    providers.filter((p) => p.cost > 0).map((p) => ({
      name: p.provider,
      value: p.cost,
      fill: providerColor(p.provider),
    })),
  [providers]);

  return (
    <div className="flex h-full">
      <div className="flex-1 overflow-auto p-4 space-y-6">
        {/* Stat cards */}
        <StatCards cards={[
          { label: 'Total Tokens', value: fmtTokens(totalTokens) },
          { label: 'Total Cost', value: fmtCost(totalCost) },
          { label: 'API Calls', value: totalCalls },
          { label: 'Models', value: models.length },
        ]} />

        {/* Charts row */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          {/* Token timeline (stacked bar by model) */}
          <div className="bg-base-100 border border-base-300 rounded-lg p-3 shadow-xs">
            <h3 className="text-xs font-semibold text-base-content/70 mb-2">Tokens Over Time</h3>
            {tokenTimeline.length > 0 ? (
              <ResponsiveContainer width="100%" height={200}>
                <BarChart data={tokenTimeline}>
                  <XAxis dataKey="bucket" tick={false} />
                  <YAxis width={50} tickFormatter={fmtTokens} />
                  <Tooltip formatter={(v: number) => fmtTokens(v)} />
                  {modelNames.map((m) => (
                    <Bar
                      key={m}
                      dataKey={m}
                      stackId="tokens"
                      fill={modelColor(m, models.find((md) => md.model === m)?.provider ?? 'unknown')}
                    />
                  ))}
                </BarChart>
              </ResponsiveContainer>
            ) : (
              <div className="flex items-center justify-center h-48 text-base-content/30 text-sm">No data yet</div>
            )}
          </div>

          {/* Cost by provider pie */}
          <div className="bg-base-100 border border-base-300 rounded-lg p-3 shadow-xs">
            <h3 className="text-xs font-semibold text-base-content/70 mb-2">Cost by Provider</h3>
            {costPieData.length > 0 ? (
              <ResponsiveContainer width="100%" height={200}>
                <PieChart>
                  <Pie data={costPieData} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={70} label={({ name }) => name}>
                    {costPieData.map((entry, i) => (
                      <Cell key={i} fill={entry.fill} />
                    ))}
                  </Pie>
                  <Tooltip formatter={(v: number) => fmtCost(v)} />
                </PieChart>
              </ResponsiveContainer>
            ) : (
              <div className="flex items-center justify-center h-48 text-base-content/30 text-sm">No data yet</div>
            )}
          </div>
        </div>

        {/* Model breakdown table */}
        {models.length > 0 && (
          <div className="bg-base-100 border border-base-300 rounded-lg p-3 shadow-xs">
            <h3 className="text-xs font-semibold text-base-content/70 mb-2">Models</h3>
            <div className="overflow-x-auto">
              <table className="table table-xs">
                <thead>
                  <tr>
                    <th>Model</th>
                    <th>Provider</th>
                    <th className="text-right">Input</th>
                    <th className="text-right">Output</th>
                    <th className="text-right">Cost</th>
                    <th className="text-right">Calls</th>
                  </tr>
                </thead>
                <tbody>
                  {models.map((m) => (
                    <tr key={m.model}>
                      <td className="font-mono text-xs">{m.model}</td>
                      <td>
                        <span className="inline-block w-2 h-2 rounded-full mr-1" style={{ backgroundColor: providerColor(m.provider) }} />
                        {m.provider}
                      </td>
                      <td className="text-right font-mono">{fmtTokens(m.input_tokens)}</td>
                      <td className="text-right font-mono">{fmtTokens(m.output_tokens)}</td>
                      <td className="text-right font-mono">{fmtCost(m.cost)}</td>
                      <td className="text-right font-mono">{m.call_count}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Trace viewer */}
        <div>
          <h3 className="text-xs font-semibold text-base-content/70 mb-2">Recent Traces</h3>
          {traces.length === 0 ? (
            <div className="text-base-content/30 text-sm py-4 text-center">No traces yet</div>
          ) : (
            <div className="space-y-1">
              {traces.map((trace) => (
                <div key={trace.trace_id} className="bg-[--color-base-100] rounded-lg overflow-hidden">
                  {/* Trace header row */}
                  <button
                    className="w-full flex items-center gap-2 px-3 py-2 text-left hover:bg-base-300 transition-colors"
                    onClick={() => toggleTrace(trace.trace_id)}
                  >
                    {expandedTrace === trace.trace_id ? (
                      <ChevronDown className="size-3 shrink-0" />
                    ) : (
                      <ChevronRight className="size-3 shrink-0" />
                    )}
                    <span className="inline-block w-2 h-2 rounded-full shrink-0" style={{ backgroundColor: providerColor(trace.provider) }} />
                    <span className="text-xs font-mono truncate flex-1">{trace.model}</span>
                    <span className="text-xs text-base-content/50">{fmtTokens(trace.total_input_tokens + trace.total_output_tokens)} tok</span>
                    <span className="text-xs text-base-content/50">{fmtDuration(trace.total_duration_ms)}</span>
                    <span className="text-xs text-base-content/50">{fmtCost(trace.total_cost)}</span>
                    {trace.total_tool_calls > 0 && (
                      <span className="badge badge-xs badge-ghost">{trace.total_tool_calls} tools</span>
                    )}
                  </button>

                  {/* Expanded trace detail */}
                  {expandedTrace === trace.trace_id && (
                    <div className="border-t border-base-300 px-3 py-2 space-y-1">
                      {traceCalls.map((call) => {
                        const callTools = traceToolCalls.filter((t) => t.model_call_id === call.id);
                        return (
                          <div key={call.id} className="space-y-1">
                            {/* Model call row */}
                            <div className="flex items-center gap-2 text-xs">
                              <span className="w-2 h-2 rounded-full shrink-0" style={{ backgroundColor: modelColor(call.model, call.provider) }} />
                              <span className="font-mono truncate">{call.model}</span>
                              <span className="text-base-content/50">{fmtTokens(call.input_tokens + call.output_tokens)}</span>
                              <span className="text-base-content/50">{fmtDuration(call.duration_ms)}</span>
                              <span className="flex-1" />
                              {call.thinking_content && (
                                <button
                                  className="btn btn-ghost btn-xs text-info"
                                  onClick={() => setDetail({ type: 'thinking', data: call as unknown as Record<string, unknown> })}
                                >
                                  thinking
                                </button>
                              )}
                              {call.text_content && (
                                <button
                                  className="btn btn-ghost btn-xs"
                                  onClick={() => setDetail({ type: 'text', data: call as unknown as Record<string, unknown> })}
                                >
                                  response
                                </button>
                              )}
                            </div>
                            {/* Tool calls within this model call */}
                            {callTools.map((tc) => {
                              const resp = traceToolResponses.find((r) => r.call_id === tc.call_id && r.model_call_id === tc.model_call_id);
                              return (
                                <button
                                  key={tc.id}
                                  className="flex items-center gap-2 text-xs pl-5 w-full text-left hover:bg-base-300 rounded py-0.5 transition-colors"
                                  onClick={() => setDetail({
                                    type: 'tool',
                                    data: { ...tc, response_preview: resp?.content_preview, is_error: resp?.is_error } as unknown as Record<string, unknown>,
                                  })}
                                >
                                  <span className="text-warning">⚡</span>
                                  <span className="font-mono truncate">{tc.tool_name}</span>
                                  {resp?.is_error ? <span className="badge badge-xs badge-error">err</span> : null}
                                </button>
                              );
                            })}
                          </div>
                        );
                      })}
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Detail panel */}
      {detail && <DetailPanel selection={detail} onClose={() => setDetail(null)} />}
    </div>
  );
}
