// frontend/src/lib/views/stats/DetailPanel.tsx
// DetailPanel -- shows detail for a selected span in the trace viewer
import { useMemo } from 'react';
import { CloseIcon } from '../../icons/Icons';
import type { DetailSelection } from '../../types';

interface Props {
  selection: DetailSelection;
  onClose: () => void;
}

/** Safely coerce an unknown value to a renderable string. */
function str(v: unknown): string {
  if (v == null) return '';
  return String(v);
}

function highlightJson(raw: string): string {
  try {
    const obj = JSON.parse(raw);
    const pretty = JSON.stringify(obj, null, 2);
    return pretty
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"([^"]+)":/g, '<span class="json-key">"$1"</span>:')
      .replace(/: "([^"]*)"/g, ': <span class="json-string">"$1"</span>')
      .replace(/: (\d+\.?\d*)/g, ': <span class="json-number">$1</span>')
      .replace(/: (true|false|null)/g, ': <span class="json-bool">$1</span>');
  } catch {
    return raw.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }
}

function formatContent(content: string | null | undefined): string {
  if (!content) return '';
  return content;
}

export default function DetailPanel({ selection, onClose }: Props) {
  const { type, data } = selection;

  const title = useMemo(() => {
    switch (type) {
      case 'thinking': return 'Thinking';
      case 'text': return 'Response';
      case 'tool': return `Tool: ${data.tool_name ?? 'unknown'}`;
      case 'net_event': return `Network: ${data.method ?? ''} ${data.domain ?? ''}`;
      case 'mcp_call': return `MCP: ${data.tool_name ?? data.method ?? 'call'}`;
      case 'file_event': return `File: ${data.action ?? ''} ${data.path ?? ''}`;
      default: return 'Detail';
    }
  }, [type, data]);

  const renderThinking = () => (
    <div className="whitespace-pre-wrap text-sm font-mono text-base-content/80 leading-relaxed">
      {formatContent(str(data.thinking_content))}
    </div>
  );

  const renderText = () => (
    <div className="whitespace-pre-wrap text-sm text-base-content leading-relaxed">
      {formatContent(str(data.text_content))}
    </div>
  );

  const renderTool = () => (
    <div className="space-y-3">
      <div>
        <div className="text-xs text-base-content/50 mb-1">Tool Name</div>
        <div className="font-mono text-sm">{str(data.tool_name)}</div>
      </div>
      {!!data.arguments && (
        <div>
          <div className="text-xs text-base-content/50 mb-1">Arguments</div>
          <pre
            className="text-xs font-mono bg-base-200 rounded p-2 overflow-auto max-h-60"
            dangerouslySetInnerHTML={{ __html: highlightJson(str(data.arguments)) }}
          />
        </div>
      )}
      {!!data.response_preview && (
        <div>
          <div className="text-xs text-base-content/50 mb-1">Response</div>
          <pre className="text-xs font-mono bg-base-200 rounded p-2 overflow-auto max-h-60">
            {str(data.response_preview)}
          </pre>
        </div>
      )}
      {data.is_error ? (
        <div className="badge bg-denied/15 text-denied badge-sm">Error</div>
      ) : null}
    </div>
  );

  const renderNetEvent = () => (
    <div className="space-y-3">
      <div className="grid grid-cols-2 gap-2 text-sm">
        <div>
          <div className="text-xs text-base-content/50">Domain</div>
          <div className="font-mono">{str(data.domain)}</div>
        </div>
        <div>
          <div className="text-xs text-base-content/50">Method</div>
          <div className="font-mono">{str(data.method) || '-'}</div>
        </div>
        <div>
          <div className="text-xs text-base-content/50">Status</div>
          <div className="font-mono">{str(data.status_code) || '-'}</div>
        </div>
        <div>
          <div className="text-xs text-base-content/50">Decision</div>
          <div className={`font-mono ${data.decision === 'allowed' ? 'text-allowed' : 'text-denied'}`}>
            {str(data.decision)}
          </div>
        </div>
        <div>
          <div className="text-xs text-base-content/50">Path</div>
          <div className="font-mono truncate">{str(data.path) || '/'}</div>
        </div>
        <div>
          <div className="text-xs text-base-content/50">Duration</div>
          <div className="font-mono">{data.duration_ms ? `${data.duration_ms}ms` : '-'}</div>
        </div>
      </div>
      {!!data.request_body_preview && (
        <div>
          <div className="text-xs text-base-content/50 mb-1">Request Body</div>
          <pre className="text-xs font-mono bg-base-200 rounded p-2 overflow-auto max-h-40">
            {str(data.request_body_preview)}
          </pre>
        </div>
      )}
      {!!data.response_body_preview && (
        <div>
          <div className="text-xs text-base-content/50 mb-1">Response Body</div>
          <pre className="text-xs font-mono bg-base-200 rounded p-2 overflow-auto max-h-40">
            {str(data.response_body_preview)}
          </pre>
        </div>
      )}
    </div>
  );

  const renderMcpCall = () => (
    <div className="space-y-3">
      <div className="grid grid-cols-2 gap-2 text-sm">
        <div>
          <div className="text-xs text-base-content/50">Server</div>
          <div className="font-mono">{str(data.server_name)}</div>
        </div>
        <div>
          <div className="text-xs text-base-content/50">Tool</div>
          <div className="font-mono">{str(data.tool_name) || str(data.method)}</div>
        </div>
        <div>
          <div className="text-xs text-base-content/50">Decision</div>
          <div className={`font-mono ${data.decision === 'allowed' ? 'text-allowed' : 'text-denied'}`}>
            {str(data.decision)}
          </div>
        </div>
        <div>
          <div className="text-xs text-base-content/50">Duration</div>
          <div className="font-mono">{data.duration_ms ? `${data.duration_ms}ms` : '-'}</div>
        </div>
      </div>
      {!!data.arguments && (
        <div>
          <div className="text-xs text-base-content/50 mb-1">Arguments</div>
          <pre
            className="text-xs font-mono bg-base-300 rounded p-2 overflow-auto max-h-60"
            dangerouslySetInnerHTML={{ __html: highlightJson(str(data.arguments)) }}
          />
        </div>
      )}
      {!!data.response_preview && (
        <div>
          <div className="text-xs text-base-content/50 mb-1">Response</div>
          <pre className="text-xs font-mono bg-base-300 rounded p-2 overflow-auto max-h-60">
            {str(data.response_preview)}
          </pre>
        </div>
      )}
    </div>
  );

  const renderFileEvent = () => (
    <div className="space-y-3">
      <div className="grid grid-cols-2 gap-2 text-sm">
        <div>
          <div className="text-xs text-base-content/50">Action</div>
          <div className="font-mono">{str(data.action)}</div>
        </div>
        <div>
          <div className="text-xs text-base-content/50">Path</div>
          <div className="font-mono truncate">{str(data.path)}</div>
        </div>
        {data.size != null && (
          <div>
            <div className="text-xs text-base-content/50">Size</div>
            <div className="font-mono">{str(data.size)} bytes</div>
          </div>
        )}
      </div>
    </div>
  );

  return (
  <div className="border-l border-base-300 bg-[--color-base-100] w-80 flex flex-col overflow-hidden">
      <div className="flex items-center justify-between px-3 py-2 border-b border-base-300">
        <h3 className="text-sm font-semibold truncate">{title}</h3>
        <button className="btn btn-ghost btn-xs" onClick={onClose}>
          <CloseIcon className="size-4" />
        </button>
      </div>
      <div className="flex-1 overflow-auto p-3">
        {type === 'thinking' && renderThinking()}
        {type === 'text' && renderText()}
        {type === 'tool' && renderTool()}
        {type === 'net_event' && renderNetEvent()}
        {type === 'mcp_call' && renderMcpCall()}
        {type === 'file_event' && renderFileEvent()}
      </div>
    </div>
  );
}

// frontend/src/lib/views/stats/DetailPanel.svelte
<script lang="ts">
  import type { DetailSelection } from '../../types';

  let { selection, onClose }: {
    selection: DetailSelection;
    onClose: () => void;
  } = $props();

  /** Simple JSON syntax highlighter -- returns HTML with colored spans. */
  function highlightJson(text: string): string {
    let formatted: string;
    try {
      formatted = JSON.stringify(JSON.parse(text), null, 2);
    } catch {
      formatted = text;
    }
    const escaped = formatted
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');
    return escaped
      .replace(
        /("(?:[^"\\]|\\.)*")(\s*:)?/g,
        (_, str, colon) => {
          if (colon) return `<span class="json-key">${str}</span>${colon}`;
          return `<span class="json-string">${str}</span>`;
        },
      )
      .replace(/\b(true|false|null)\b/g, '<span class="json-bool">$1</span>')
      .replace(/\b(-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?)\b/g, '<span class="json-number">$1</span>');
  }

  function tryHighlight(text: string | null | undefined): string {
    if (!text) return '<span class="text-base-content/30">(empty)</span>';
    // Try JSON-highlighting; if it starts with { or [, assume JSON.
    const trimmed = text.trim();
    if (trimmed.startsWith('{') || trimmed.startsWith('[')) {
      return highlightJson(trimmed);
    }
    return trimmed.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }

  const d = $derived(selection.data);
</script>

<div class="card w-[400px] flex-shrink-0 border-l border-base-300 flex flex-col overflow-hidden bg-base-100 rounded-none">
  <!-- Header -->
  <div class="flex items-center gap-2 px-3 py-2 border-b border-base-300 bg-base-200/40">
    <span class="text-xs font-semibold flex-1 truncate capitalize">{selection.type.replace('_', ' ')}</span>
    <button class="btn btn-ghost btn-xs" onclick={onClose} aria-label="Close detail panel">
      <svg class="size-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
    </button>
  </div>

  <!-- Content -->
  <div class="flex-1 overflow-auto p-3 text-xs space-y-3">
    {#if selection.type === 'thinking'}
      <div>
        <div class="text-[10px] font-semibold text-base-content/40 uppercase tracking-wider mb-1">Thinking</div>
        <pre class="font-mono text-xs whitespace-pre-wrap break-words leading-relaxed bg-base-200/30 rounded p-2 max-h-[80vh] overflow-auto">{d.thinking_content ?? '(empty)'}</pre>
      </div>

    {:else if selection.type === 'text'}
      <div>
        <div class="text-[10px] font-semibold text-base-content/40 uppercase tracking-wider mb-1">Response</div>
        <pre class="font-mono text-xs whitespace-pre-wrap break-words leading-relaxed bg-base-200/30 rounded p-2 max-h-[80vh] overflow-auto">{d.text_content ?? '(empty)'}</pre>
      </div>

    {:else if selection.type === 'tool'}
      <div>
        <div class="text-[10px] font-semibold text-base-content/40 uppercase tracking-wider mb-1">
          {d.tool_name ?? 'Tool'}
          {#if d.origin && d.origin !== 'native'}
            <span class="badge badge-xs badge-outline ml-1">{d.origin}</span>
          {/if}
        </div>
      </div>
      <div>
        <div class="text-[10px] font-semibold text-base-content/40 uppercase tracking-wider mb-1">Arguments</div>
        <pre class="font-mono text-xs whitespace-pre-wrap break-words leading-relaxed bg-base-200/30 rounded p-2 overflow-auto max-h-64">{@html tryHighlight(d.arguments as string)}</pre>
      </div>
      {#if d.content_preview !== undefined}
        <div>
          <div class="text-[10px] font-semibold text-base-content/40 uppercase tracking-wider mb-1">
            Result
            {#if d.is_error}
              <span class="badge badge-xs bg-denied/15 text-denied ml-1">error</span>
            {/if}
          </div>
          <pre class="font-mono text-xs whitespace-pre-wrap break-words leading-relaxed bg-base-200/30 rounded p-2 overflow-auto max-h-64">{@html tryHighlight(d.content_preview as string)}</pre>
        </div>
      {/if}

    {:else if selection.type === 'net_event'}
      <div>
        <div class="text-[10px] font-semibold text-base-content/40 uppercase tracking-wider mb-1">Request</div>
        <div class="space-y-1">
          <div><span class="text-base-content/40">Method:</span> <span class="font-mono">{d.method ?? 'CONNECT'}</span></div>
          <div><span class="text-base-content/40">Domain:</span> <span class="font-mono">{d.domain}</span></div>
          <div><span class="text-base-content/40">Path:</span> <span class="font-mono">{d.path ?? '/'}</span></div>
          {#if d.query}
            <div><span class="text-base-content/40">Query:</span> <span class="font-mono">{d.query}</span></div>
          {/if}
          <div>
            <span class="text-base-content/40">Decision:</span>
            <span class="badge badge-xs {d.decision === 'allowed' ? 'bg-allowed/15 text-allowed' : 'bg-denied/15 text-denied'}">{d.decision}</span>
          </div>
          {#if d.status_code}
            <div><span class="text-base-content/40">Status:</span> <span class="font-mono">{d.status_code}</span></div>
          {/if}
          {#if d.duration_ms}
            <div><span class="text-base-content/40">Duration:</span> <span class="font-mono">{d.duration_ms}ms</span></div>
          {/if}
          {#if d.matched_rule}
            <div><span class="text-base-content/40">Rule:</span> <span class="font-mono">{d.matched_rule}</span></div>
          {/if}
        </div>
      </div>
      {#if d.request_headers}
        <div>
          <div class="text-[10px] font-semibold text-base-content/40 uppercase tracking-wider mb-1">Request Headers</div>
          <pre class="font-mono text-xs whitespace-pre-wrap break-words leading-relaxed bg-base-200/30 rounded p-2 overflow-auto max-h-40">{@html tryHighlight(d.request_headers as string)}</pre>
        </div>
      {/if}
      {#if d.request_body_preview}
        <div>
          <div class="text-[10px] font-semibold text-base-content/40 uppercase tracking-wider mb-1">Request Body</div>
          <pre class="font-mono text-xs whitespace-pre-wrap break-words leading-relaxed bg-base-200/30 rounded p-2 overflow-auto max-h-40">{@html tryHighlight(d.request_body_preview as string)}</pre>
        </div>
      {/if}
      {#if d.response_headers}
        <div>
          <div class="text-[10px] font-semibold text-base-content/40 uppercase tracking-wider mb-1">Response Headers</div>
          <pre class="font-mono text-xs whitespace-pre-wrap break-words leading-relaxed bg-base-200/30 rounded p-2 overflow-auto max-h-40">{@html tryHighlight(d.response_headers as string)}</pre>
        </div>
      {/if}
      {#if d.response_body_preview}
        <div>
          <div class="text-[10px] font-semibold text-base-content/40 uppercase tracking-wider mb-1">Response Body</div>
          <pre class="font-mono text-xs whitespace-pre-wrap break-words leading-relaxed bg-base-200/30 rounded p-2 overflow-auto max-h-40">{@html tryHighlight(d.response_body_preview as string)}</pre>
        </div>
      {/if}

    {:else if selection.type === 'mcp_call'}
      <div class="space-y-1">
        <div><span class="text-base-content/40">Server:</span> <span class="font-mono">{d.server_name}</span></div>
        <div><span class="text-base-content/40">Method:</span> <span class="font-mono">{d.method}</span></div>
        {#if d.tool_name}
          <div><span class="text-base-content/40">Tool:</span> <span class="font-mono">{d.tool_name}</span></div>
        {/if}
        <div>
          <span class="text-base-content/40">Decision:</span>
          <span class="badge badge-xs {d.decision === 'allowed' ? 'bg-allowed/15 text-allowed' : 'bg-denied/15 text-denied'}">{d.decision}</span>
        </div>
        {#if d.duration_ms}
          <div><span class="text-base-content/40">Duration:</span> <span class="font-mono">{d.duration_ms}ms</span></div>
        {/if}
        {#if d.error_message}
          <div><span class="text-base-content/40">Error:</span> <span class="text-denied">{d.error_message}</span></div>
        {/if}
      </div>
      {#if d.request_preview}
        <div>
          <div class="text-[10px] font-semibold text-base-content/40 uppercase tracking-wider mb-1">Request</div>
          <pre class="font-mono text-xs whitespace-pre-wrap break-words leading-relaxed bg-base-200/30 rounded p-2 overflow-auto max-h-48">{@html tryHighlight(d.request_preview as string)}</pre>
        </div>
      {/if}
      {#if d.response_preview}
        <div>
          <div class="text-[10px] font-semibold text-base-content/40 uppercase tracking-wider mb-1">Response</div>
          <pre class="font-mono text-xs whitespace-pre-wrap break-words leading-relaxed bg-base-200/30 rounded p-2 overflow-auto max-h-48">{@html tryHighlight(d.response_preview as string)}</pre>
        </div>
      {/if}

    {:else if selection.type === 'file_event'}
      <div class="space-y-1">
        <div><span class="text-base-content/40">Action:</span>
          <span class="badge badge-xs {d.action === 'deleted' ? 'bg-file-deleted/15 text-file-deleted' : d.action === 'created' ? 'bg-file-created/15 text-file-created' : 'bg-file-modified/15 text-file-modified'}">{d.action}</span>
        </div>
        <div><span class="text-base-content/40">Path:</span> <span class="font-mono break-all">{d.path}</span></div>
        {#if d.size != null}
          <div><span class="text-base-content/40">Size:</span> <span class="font-mono">{d.size} bytes</span></div>
        {/if}
        {#if d.timestamp}
          <div><span class="text-base-content/40">Time:</span> <span class="font-mono">{d.timestamp}</span></div>
        {/if}
      </div>
    {/if}
  </div>
</div>
