// frontend/src/lib/views/stats/StatCards.svelte
<script lang="ts">
  interface StatCard {
    label: string;
    value: string | number;
    sub?: string;
    colorClass?: string;
  }

  let { cards }: { cards: StatCard[] } = $props();
</script>

<div class="flex gap-3 px-3 py-2">
  {#each cards as card}
    <div class="stat p-2 bg-base-200/40 rounded-lg flex-1 min-w-0">
      <div class="stat-title text-[10px] uppercase tracking-wider text-base-content/40">{card.label}</div>
      <div class="stat-value text-lg font-bold {card.colorClass ?? ''}">{card.value}</div>
      {#if card.sub}
        <div class="stat-desc text-[10px] text-base-content/30">{card.sub}</div>
      {/if}
    </div>
  {/each}
</div>

// frontend/src/lib/views/stats/StatCards.tsx
// StatCards -- grid of summary statistic cards for stats tabs
import type { ReactNode } from 'react';

export interface StatCard {
  label: string;
  value: string | number;
  detail?: string;
  color?: string;
}

interface Props {
  cards: StatCard[];
}

export default function StatCards({ cards }: Props) {
  return (
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
      {cards.map((card, i) => (
        <div key={i} className="bg-base-200 rounded-lg p-3">
          <div className="text-xs text-base-content/60 uppercase tracking-wider">{card.label}</div>
          <div className="text-xl font-bold mt-1" style={card.color ? { color: card.color } : undefined}>
            {card.value}
          </div>
          {card.detail && (
            <div className="text-xs text-base-content/50 mt-0.5">{card.detail}</div>
          )}
        </div>
      ))}
    </div>
  );
}
