// frontend/src/lib/views/StatsView.tsx
// StatsView -- tabbed stats panel with sub-menu
import { useStats, setStatsTab } from '../stores/stats';
import SubMenu from '../components/SubMenu';
import AITab from './stats/AITab';
import ToolsTab from './stats/ToolsTab';
import NetworkTab from './stats/NetworkTab';
import FilesTab from './stats/FilesTab';
import type { StatsTab as StatsTabType } from '../types';

const TABS: { id: StatsTabType; label: string }[] = [
  { id: 'ai', label: 'AI' },
  { id: 'tools', label: 'Tools' },
  { id: 'network', label: 'Network' },
  { id: 'files', label: 'Files' },
];

export default function StatsView() {
  const { activeTab } = useStats();

  return (
    <div className="flex h-full w-full">
      <SubMenu
        groups={[{ label: 'Stats', items: TABS.map((t) => ({ id: t.id, label: t.label })) }]}
        active={activeTab}
        onSelect={(id) => setStatsTab(id as StatsTabType)}
      />
      <div className="flex-1 min-w-0 overflow-hidden">
        {activeTab === 'ai' && <AITab />}
        {activeTab === 'tools' && <ToolsTab />}
        {activeTab === 'network' && <NetworkTab />}
        {activeTab === 'files' && <FilesTab />}
      </div>
    </div>
  );
}

// frontend/src/lib/views/StatsView.svelte
<script lang="ts">
  import SubMenu from '../components/SubMenu.svelte';
  import { statsStore } from '../stores/stats.svelte';
  import type { StatsTab } from '../types';
  import AITab from './stats/AITab.svelte';
  import ToolsTab from './stats/ToolsTab.svelte';
  import NetworkTab from './stats/NetworkTab.svelte';
  import FilesTab from './stats/FilesTab.svelte';

  const groups = [
    {
      label: '',
      items: [
        { id: 'ai', label: 'Model' },
        { id: 'tools', label: 'Tools' },
        { id: 'network', label: 'Network' },
        { id: 'files', label: 'Files' },
      ],
    },
  ];

  function onSelect(id: string) {
    statsStore.setTab(id as StatsTab);
  }
</script>

<div class="flex h-full overflow-hidden">
  <SubMenu {groups} active={statsStore.activeTab} {onSelect} />
  <div class="flex-1 min-h-0 overflow-hidden">
    {#if statsStore.activeTab === 'ai'}
      <AITab />
    {:else if statsStore.activeTab === 'tools'}
      <ToolsTab />
    {:else if statsStore.activeTab === 'network'}
      <NetworkTab />
    {:else if statsStore.activeTab === 'files'}
      <FilesTab />
    {/if}
  </div>
</div>
