// frontend/src/lib/views/WizardView.svelte
<script lang="ts">
  import { sidebarStore } from '../stores/sidebar.svelte';
  import { settingsStore } from '../stores/settings.svelte';
</script>

<div class="flex h-full items-center justify-center">
  <div class="text-center max-w-md space-y-4">
    <h1 class="text-2xl font-semibold">Welcome to Capsem</h1>
    <p class="text-sm text-base-content/60">Get started by configuring an AI provider with an API key. You can always change this later in Settings.</p>
    <div class="flex justify-center gap-3 pt-2">
      <button
        class="btn bg-interactive text-white btn-sm"
        onclick={() => {
          const first = settingsStore.sections[0] || 'AI Providers';
          sidebarStore.setSettingsSection(first);
          sidebarStore.setView('settings');
        }}
      >
        Configure Providers
      </button>
      <button
        class="btn btn-ghost btn-sm"
        onclick={() => sidebarStore.setView('terminal')}
      >
        Skip for now
      </button>
    </div>
  </div>
</div>

// frontend/src/lib/views/WizardView.tsx
// WizardView -- simple onboarding prompt for initial setup
import { useSidebar } from '../stores/sidebar';
import { useSettings } from '../stores/settings';

export default function WizardView() {
  const { setView, setSettingsSection } = useSidebar();
  const { sections } = useSettings();

  function goToSettings() {
    const providerSection = sections.find((s) => s.toLowerCase().includes('provider') || s.toLowerCase().includes('api'));
    if (providerSection) setSettingsSection(providerSection);
    setView('settings');
  }

  return (
    <div className="flex items-center justify-center h-full w-full bg-base-100">
      <div className="text-center max-w-md space-y-6 px-4">
        <h1 className="text-3xl font-bold text-base-content">Welcome to AI.VM</h1>
        <p className="text-base-content/70">
          To get started, configure at least one AI provider API key in Settings.
        </p>
        <button
          className="btn btn-primary btn-wide"
          onClick={goToSettings}
        >
          Open Settings
        </button>
      </div>
    </div>
  );
}
