// frontend/src/lib/App.tsx
// App -- main shell component
import { useEffect, Component, type ReactNode, type ErrorInfo } from 'react';
import { useSidebar } from './stores/sidebar';
import { useVm, initVm } from './stores/vm';
import { loadSettings } from './stores/settings';
import { initTheme } from './stores/theme';

import Sidebar from './components/Sidebar';
import StatusBar from './components/StatusBar';
import DownloadProgress from './components/DownloadProgress';
import ThemeToggle from './components/ThemeToggle';

import TerminalView from './views/TerminalView';
import StatsView from './views/StatsView';
import SettingsView from './views/SettingsView';
import WizardView from './views/WizardView';

// Error boundary to catch rendering crashes
class ErrorBoundary extends Component<{ children: ReactNode }, { error: Error | null }> {
  constructor(props: { children: ReactNode }) {
    super(props);
    this.state = { error: null };
  }
  static getDerivedStateFromError(error: Error) {
    return { error };
  }
  componentDidCatch(error: Error, info: ErrorInfo) {
    console.error('[ErrorBoundary]', error, info.componentStack);
  }
  render() {
    if (this.state.error) {
      return (
        <div style={{ padding: 24, color: '#f66', fontFamily: 'monospace', whiteSpace: 'pre-wrap' }}>
          <h2>UI Error</h2>
          <p>{this.state.error.message}</p>
          <pre style={{ fontSize: 11, opacity: 0.7, marginTop: 8 }}>{this.state.error.stack}</pre>
        </div>
      );
    }
    return this.props.children;
  }
}

function AppInner() {
  const { activeView } = useSidebar();
  const { isDownloading, downloadProgress } = useVm();
  // Initialize on mount
  useEffect(() => {
    initTheme();
    initVm();
    loadSettings();
  }, []);

  const currentView = activeView;

  return (
    <div className="flex h-screen w-screen overflow-hidden bg-base-100 text-base-content">
      <Sidebar />
      <div className="flex-1 flex flex-col min-w-0 overflow-hidden relative">
        {/* Top bar with theme toggle */}
        <div className="flex items-center justify-end px-2 py-1 border-b border-base-300 bg-base-100/80 backdrop-blur-sm z-10">
          <ThemeToggle />
        </div>

        {/* Download overlay */}
        {isDownloading && downloadProgress && (
          <div className="absolute inset-0 z-50 flex items-center justify-center bg-base-100/90 backdrop-blur-sm">
            <DownloadProgress />
          </div>
        )}

        {/* Main content area */}
        <div className="flex-1 min-h-0 overflow-hidden">
          {currentView === 'terminal' && <TerminalView />}
          {currentView === 'stats' && <StatsView />}
          {currentView === 'settings' && <SettingsView />}
          {currentView === 'wizard' && <WizardView />}
        </div>

        {/* Status bar */}
        <StatusBar />
      </div>
    </div>
  );
}

export default function App() {
  return (
    <ErrorBoundary>
      <AppInner />
    </ErrorBoundary>
  );
}

// frontend/src/lib/components/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import Sidebar from './Sidebar.svelte';
  import DownloadProgress from './DownloadProgress.svelte';
  import TerminalView from '../views/TerminalView.svelte';
  import StatsView from '../views/StatsView.svelte';
  import SettingsView from '../views/SettingsView.svelte';
  import WizardView from '../views/WizardView.svelte';
  import { sidebarStore } from '../stores/sidebar.svelte';
  import { settingsStore } from '../stores/settings.svelte';
  import { themeStore } from '../stores/theme.svelte';
  import { vmStore } from '../stores/vm.svelte';

  let checkedFirstRun = $state(false);

  onMount(() => {
    themeStore.init();
    vmStore.init();
    settingsStore.load();
  });

  $effect(() => {
    if (!checkedFirstRun && !settingsStore.loading && settingsStore.tree.length > 0) {
      checkedFirstRun = true;
    }
  });
</script>

<div class="flex h-screen w-screen overflow-hidden bg-base-100 text-base-content">
  <Sidebar />
  <div class="flex flex-1 flex-col min-w-0">
    {#if vmStore.isDownloading}
      <DownloadProgress />
    {:else}
      <!-- Content area: terminal is always mounted, hidden with visibility to avoid refit flash -->
      <div class="flex-1 min-h-0 relative">
        <div
          class="absolute inset-0"
          style:visibility={sidebarStore.activeView === 'terminal' ? 'visible' : 'hidden'}
        >
          <TerminalView />
        </div>
        {#if sidebarStore.activeView === 'stats'}
          <StatsView />
        {:else if sidebarStore.activeView === 'settings'}
          <SettingsView />
        {:else if sidebarStore.activeView === 'wizard'}
          <WizardView />
        {/if}
      </div>
    {/if}
  </div>
</div>
