// frontend/src/lib/components/Sidebar.svelte
<script lang="ts">
  import { sidebarStore } from '../stores/sidebar.svelte';
  import type { ViewName } from '../types';
  import type { Component } from 'svelte';
  import TerminalIcon from '../icons/TerminalIcon.svelte';
  import SettingsIcon from '../icons/SettingsIcon.svelte';

  const items: { view: ViewName; label: string; icon: Component<{ class?: string }> }[] = [
    { view: 'terminal', label: 'Console', icon: TerminalIcon },
    { view: 'settings', label: 'Settings', icon: SettingsIcon },
  ];
</script>

<aside
  class="flex flex-col flex-shrink-0 border-r border-base-300 bg-base-200 w-12 overflow-hidden"
>
  <nav class="flex-1 py-2">
    <ul class="menu menu-vertical gap-1 px-1.5">
      {#each items as item}
        {@const isActive = sidebarStore.activeView === item.view}
        {@const Icon = item.icon}
        <li>
          <button
            class="flex items-center justify-center px-2 py-2 {isActive ? 'menu-active' : ''}"
            onclick={() => sidebarStore.setView(item.view)}
            title={item.label}
          >
            <Icon class="size-5" />
          </button>
        </li>
      {/each}
    </ul>
  </nav>
</aside>

// frontend/src/lib/components/Sidebar.tsx
// Sidebar component
import { useSidebar } from '../stores/sidebar';
import { TerminalIcon, SettingsIcon } from '../icons/Icons';
import type { ViewName } from '../types';
import type { FC } from 'react';

const items: { view: ViewName; label: string; Icon: FC<{ className?: string }> }[] = [
  { view: 'terminal', label: 'Console', Icon: TerminalIcon },
  { view: 'settings', label: 'Settings', Icon: SettingsIcon },
];

export default function Sidebar() {
  const { activeView, setView } = useSidebar();

  return (
    <aside className="flex flex-col flex-shrink-0 border-r border-base-300 bg-black w-12 overflow-hidden">
      <nav className="flex-1 py-2">
        <ul className="menu menu-vertical gap-1 px-1.5">
          {items.map((item) => (
            <li key={item.view}>
              <button
                className={`flex items-center justify-center px-2 py-2 ${activeView === item.view ? 'menu-active' : ''}`}
                onClick={() => setView(item.view)}
                title={item.label}
              >
                <item.Icon className="size-5" />
              </button>
            </li>
          ))}
        </ul>
      </nav>
    </aside>
  );
}
